export const countries = [
  { name: "Afghanistan" },
  { name: "Australia" },
  { name: "Bangladesh" },
  { name: "Belgium" },
  { name: "Brazil" },
  { name: "Canada" },
  { name: "China" },
  { name: "Colombia" },
  { name: "Finland" },
  { name: "France" },
  { name: "Gambia" },
  { name: "Georgia" },
  { name: "Germany" },
  { name: "Greece" },
  { name: "Hong Kong" },
  { name: "Iceland" },
  { name: "India" },
  { name: "Indonesia" },
  { name: "Iran, Islamic Republic Of" },
  { name: "Iraq" },
  { name: "Ireland" },
  { name: "Israel" },
  { name: "Italy" },
  { name: "Japan" },
  { name: "Kazakhstan" },
  { name: "Korea" },
  { name: "Kuwait" },
  { name: "Malaysia" },
  { name: "Maldives" },
  { name: "Mali" },
  { name: "Mexico" },
  { name: "Monaco" },
  { name: "Myanmar" },
  { name: "Nauru" },
  { name: "Nepal" },
  { name: "Netherlands" },
  { name: "New Zealand" },
  { name: "Nicaragua" },
  { name: "Norfolk Island" },
  { name: "Northern Mariana Islands" },
  { name: "Norway" },
  { name: "Oman" },
  { name: "Pakistan" },
  { name: "Palau" },
  { name: "Panama" },
  { name: "Paraguay" },
  { name: "Peru" },
  { name: "Philippines" },
  { name: "Pitcairn" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "Puerto Rico" },
  { name: "Qatar" },
  { name: "Reunion" },
  { name: "Romania" },
  { name: "RWANDA" },
  { name: "Saudi Arabia" },
  { name: "Senegal" },
  { name: "Seychelles" },
  { name: "Sierra Leone" },
  { name: "Singapore" },
  { name: "Slovakia" },
  { name: "Slovenia" },
  { name: "Solomon Islands" },
  { name: "Sweden" },
  { name: "Switzerland" },
  { name: "Tunisia" },
  { name: "Turkey" },
  { name: "Tuvalu" },
  { name: "Uganda" },
  { name: "Ukraine" },
  { name: "United Arab Emirates" },
  { name: "United Kingdom" },
  { name: "United States" },
  { name: "Uruguay" },
  { name: "Uzbekistan" },
  { name: "Vanuatu" },
  { name: "Venezuela" },
  { name: "VietNam" },
  { name: "Zimbabwe" },
];
export const Sizes = [
  "XXS",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
  "4XL",
  "5XL",
  "6XL",
];
export const Patterns = [
  "Solid",
  "Striped",
  "Printed",
  "Graphic",
  "Plaid",
  "Polka Dot",
  "Abstract",
  "Tie-Dye",
  "Camouflage",
  "Animal Print",
  "Geometric",
];
export const Fabrics = [
  "Cotton",
  "Polyester",
  "Silk",
  "Linen",
  "Wool",
  "Denim",
  "Rayon",
  "Spandex",
  "Nylon",
  "Leather",
  "Velvet",
];
export const Sleeves = [
  "Short Sleeve",
  "Long Sleeve",
  "Sleeveless",
  "3/4 Sleeve",
  "Cap Sleeve",
  "Puff Sleeve",
  "Bell Sleeve",
  "Cold Shoulder",
  "Off-the-Shoulder",
  "Halter Neck",
  "Kimono Sleeve",
];
export const Occasions = [
  "Casual",
  "Formal",
  "Party",
  "Sports",
  "Work",
  "Beach",
  "Travel",
  "Wedding",
  "Date Night",
  "Outdoor",
  "Gym",
];
export const SuitableFor = [
  "Men",
  "Women",
  "Unisex",
  "Kids",
  "Babies",
  "Toddlers",
  "Teens",
  "Pregnant Women",
  "Elderly",
  "Pets",
  "Couples",
];

export const TShirtTypes = [
  "V Neck",
  "U Neck",
  "Crew Neck",
  "Scoop Neck",
  "Boat Neck",
  "Square Neck",
  "Halter Neck",
  "Off-the-Shoulder",
  "One Shoulder",
  "Turtleneck",
  "Polo Neck",
  "Sweetheart Neckline",
];
